services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    volumes:
      - evolution_instances:/evolution/instances
    env_file:
      - .env
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.evo.rule=Host(`evolution.beetzap.com`)"
      - "traefik.http.routers.evo.entrypoints=websecure"
      - "traefik.http.routers.evo.tls.certresolver=letsencrypt"
      - "traefik.http.services.evo.loadbalancer.server.port=8080"

volumes:
  evolution_instances:
