services:
  
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8080

  # pgbouncer:
  #   image: edoburu/pgbouncer:latest
  #   environment:
  #     DB_HOST: postgres
  #     DB_USER: user
  #     DB_PASSWORD: pass
  #     POOL_MODE: transaction
  #     AUTH_TYPE: trust
  #     MAX_CLIENT_CONN: 1000
  #     DEFAULT_POOL_SIZE: 25
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "6543:5432"
  #   networks:
  #     - evolution-net

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
