services:
  api:
    container_name: evolution_api
    image: evoapicloud/evolution-api:latest
    restart: always
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    # A LINHA "expose" FOI TROCADA PELA LINHA "ports" ABAIXO
    ports:
      - "8081:8080" # Mapeia a porta 8081 do servidor para a 8080 do container

volumes:
  evolution_instances:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
